services:
  - type: web
    name: youtube-text-extractor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0"
    plan: free 